group:
  # CODEOWNERS + FUNDING.yml
  - files:
      - source: github/
        dest: .github/
    repos: |
      phnx47/pkgbuilds
      phnx47/fingerprint-builder-net
      phnx47/dapper-repositories
  # .NET renovate config
  - files:
      - source: dotnet/renovate.json
        dest: .github/renovate.json
    repos: |
      phnx47/fingerprint-builder-net
      phnx47/dapper-repositories
