group:
  # Common configs
  - files:
      - source: common/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: common/FUNDING.yml
        dest: .github/FUNDING.yml
      - source: common/labeled.yml
        dest: .github/workflows/labeled.yml
    repos: |
      phnx47/pkgbuilds
      phnx47/hvst-cli
      phnx47/fingerprint-builder
      phnx47/dapper-repositories
  # .NET configs
  - files:
      - source: dotnet/renovate.json
        dest: .github/renovate.json
      - source: dotnet/.editorconfig
        dest: .editorconfig
      - source: dotnet/Directory.Build.props
        dest: Directory.Build.props
    repos: |
      phnx47/fingerprint-builder
      phnx47/dapper-repositories
