group:
  # CODEOWNERS + FUNDING.yml
  - files:
      - source: common/
        dest: .github/
    repos: |
      phnx47/pkgbuilds
      phnx47/fingerprint-builder-net
      phnx47/dapper-repositories
  # .NET configs
  - files:
      - source: dotnet/renovate.json
        dest: .github/renovate.json
      - source: dotnet/.editorconfig
        dest: .editorconfig
    repos: |
      phnx47/fingerprint-builder-net
      phnx47/dapper-repositories
